SELECT
  T3.AMOUNT AS SALARY,
  CONCAT(T1.FIRST_NAME, ' ', T1.LAST_NAME) AS NAME,
  YEAR(CURDATE()) - YEAR(T1.DOB) AS AGE,
  T2.DEPARTMENT_NAME
FROM EMPLOYEE AS T1
JOIN DEPARTMENT AS T2
  ON T1.DEPARTMENT = T2.DEPARTMENT_ID
JOIN PAYMENTS AS T3
  ON T1.EMP_ID = T3.EMP_ID
WHERE
  DAY(T3.PAYMENT_TIME) != 1
ORDER BY
  T3.AMOUNT DESC
LIMIT 1;